CREATE TABLE users (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username    VARCHAR(50)  NOT NULL,
                       email       VARCHAR(100) NOT NULL UNIQUE,
                       department  VARCHAR(50),
                       role        VARCHAR(50)  NOT NULL,
                       created_at  TIMESTAMP,
                       updated_at  TIMESTAMP
);