CREATE TABLE rooms (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name        VARCHAR(100) NOT NULL UNIQUE,
                       capacity    INTEGER      NOT NULL CHECK (capacity > 0),
                       floor       VARCHAR(50),
                       location    VARCHAR(100),
                       is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
                       created_at  TIMESTAMP,
                       updated_at  TIMESTAMP
);