CREATE TABLE reservations (
                              id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              room_id         BIGINT       NOT NULL REFERENCES rooms(id),
                              user_id         BIGINT       NOT NULL REFERENCES users(id),
                              start_time      TIMESTAMP    NOT NULL,
                              end_time        TIMESTAMP    NOT NULL,
                              subject         VARCHAR(200) NOT NULL,
                              purpose         VARCHAR(500),
                              attendee_count  INTEGER      NOT NULL CHECK (attendee_count > 0),
                              status          VARCHAR(30)  NOT NULL,
                              created_at      TIMESTAMP,
                              updated_at      TIMESTAMP,
                              CHECK (start_time < end_time)
);