CREATE TABLE reservation_reviews (
                                     id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     reservation_id  BIGINT       NOT NULL REFERENCES reservations(id),
                                     reviewer_id     BIGINT       NOT NULL REFERENCES users(id),
                                     action          VARCHAR(20)  NOT NULL,
                                     comment         VARCHAR(500),
                                     reviewed_at     TIMESTAMP,
                                     created_at      TIMESTAMP,
                                     updated_at      TIMESTAMP
);